/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsInt,
  Min,
  Max,
} from "class-validator";
import { ImageUpdateManyWithoutProductsInput } from "./ImageUpdateManyWithoutProductsInput";
import { Type } from "class-transformer";
import { OrderUpdateManyWithoutProductsInput } from "./OrderUpdateManyWithoutProductsInput";
import { PriceUpdateManyWithoutProductsInput } from "./PriceUpdateManyWithoutProductsInput";
import { StockUpdateManyWithoutProductsInput } from "./StockUpdateManyWithoutProductsInput";

@InputType()
class ProductUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  additionalImages?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  articleCode?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  defaultImageUrl?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  descriptionEn?: string | null;

  @ApiProperty({
    required: false,
    type: () => ImageUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => ImageUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => ImageUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  images?: ImageUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  keywords?: string | null;

  @ApiProperty({
    required: false,
    type: () => OrderUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => OrderUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => OrderUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  orders?: OrderUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: () => PriceUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => PriceUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => PriceUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  prices?: PriceUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  quantityPerUnit?: number | null;

  @ApiProperty({
    required: false,
    type: () => StockUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => StockUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => StockUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  stocks?: StockUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  unit?: string | null;
}

export { ProductUpdateInput as ProductUpdateInput };
