/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsInt,
  Min,
  Max,
} from "class-validator";
import { ImageUpdateManyWithoutArticlesInput } from "./ImageUpdateManyWithoutArticlesInput";
import { Type } from "class-transformer";
import { OrderUpdateManyWithoutArticlesInput } from "./OrderUpdateManyWithoutArticlesInput";
import { PriceUpdateManyWithoutArticlesInput } from "./PriceUpdateManyWithoutArticlesInput";
import { StockUpdateManyWithoutArticlesInput } from "./StockUpdateManyWithoutArticlesInput";

@InputType()
class ArticleUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  additionalImages?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  articleCode?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  descriptionEn?: string | null;

  @ApiProperty({
    required: false,
    type: () => ImageUpdateManyWithoutArticlesInput,
  })
  @ValidateNested()
  @Type(() => ImageUpdateManyWithoutArticlesInput)
  @IsOptional()
  @Field(() => ImageUpdateManyWithoutArticlesInput, {
    nullable: true,
  })
  images?: ImageUpdateManyWithoutArticlesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  keywords?: string | null;

  @ApiProperty({
    required: false,
    type: () => OrderUpdateManyWithoutArticlesInput,
  })
  @ValidateNested()
  @Type(() => OrderUpdateManyWithoutArticlesInput)
  @IsOptional()
  @Field(() => OrderUpdateManyWithoutArticlesInput, {
    nullable: true,
  })
  orders?: OrderUpdateManyWithoutArticlesInput;

  @ApiProperty({
    required: false,
    type: () => PriceUpdateManyWithoutArticlesInput,
  })
  @ValidateNested()
  @Type(() => PriceUpdateManyWithoutArticlesInput)
  @IsOptional()
  @Field(() => PriceUpdateManyWithoutArticlesInput, {
    nullable: true,
  })
  prices?: PriceUpdateManyWithoutArticlesInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  quantityPerUnit?: number | null;

  @ApiProperty({
    required: false,
    type: () => StockUpdateManyWithoutArticlesInput,
  })
  @ValidateNested()
  @Type(() => StockUpdateManyWithoutArticlesInput)
  @IsOptional()
  @Field(() => StockUpdateManyWithoutArticlesInput, {
    nullable: true,
  })
  stocks?: StockUpdateManyWithoutArticlesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  unit?: string | null;
}

export { ArticleUpdateInput as ArticleUpdateInput };
